// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCANZVLimYZFQooHuvAFMMikhRVr5FtyZU',
    appId: '1:576531288403:web:b127cb70ae0f34a77811a6',
    messagingSenderId: '576531288403',
    projectId: 'jm-quick',
    authDomain: 'jm-quick.firebaseapp.com',
    storageBucket: 'jm-quick.firebasestorage.app',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOUbp3-cOHmsf2lgfExs-4xkuXMede5lY',
    appId: '1:576531288403:android:398fb28a5ed4ffd87811a6',
    messagingSenderId: '576531288403',
    projectId: 'jm-quick',
    storageBucket: 'jm-quick.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI7SKqZhXKkLteHMos6X1kmCM4eT-Pwi4',
    appId: '1:576531288403:ios:7f882f7ae59bf7fb7811a6',
    messagingSenderId: '576531288403',
    projectId: 'jm-quick',
    storageBucket: 'jm-quick.firebasestorage.app',
    iosBundleId: 'com.example.jmQuick',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI7SKqZhXKkLteHMos6X1kmCM4eT-Pwi4',
    appId: '1:576531288403:ios:7f882f7ae59bf7fb7811a6',
    messagingSenderId: '576531288403',
    projectId: 'jm-quick',
    storageBucket: 'jm-quick.firebasestorage.app',
    iosBundleId: 'com.example.jmQuick',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCANZVLimYZFQooHuvAFMMikhRVr5FtyZU',
    appId: '1:576531288403:web:1053ba0b977b09647811a6',
    messagingSenderId: '576531288403',
    projectId: 'jm-quick',
    authDomain: 'jm-quick.firebaseapp.com',
    storageBucket: 'jm-quick.firebasestorage.app',
  );
}
